version: "3"

services:
  jupyter:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.jupyter.pip
    image: aleph-jypyter:latest
    user: 1000:1000
    container_name: jupyter
    ports:
      - 10000:8888
    volumes:
      - ../notebooks:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=easy

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./postgres/config:/config
    command: postgres -c 'config_file=/config/postgresql.conf'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
      timeout: 30s
    restart: always

  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/config_local.py:/pgadmin4/config_local.py
      - ./pgadmin/pgpass:/pgpass
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 10001:80
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg-data:
